name = "RubikKociemba"
uuid = "149dba96-27df-4b68-bde6-b18903c8d25e"
authors = ["Bui Quang Minh <minhcly95@outlook.com> and contributors"]
version = "0.1.0-DEV"

[deps]
RubikCore = "a6206385-a85b-45a1-9870-e715cb6a9b8e"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
